version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPO_URI=${ECR_REPO_URI}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REPO_URI%%/*}
  build:
    commands:
      - docker build -t $REPO_URI:$IMAGE_TAG ./backend
      - docker push $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECS_CONTAINER_NAME" "$REPO_URI:$IMAGE_TAG" > pipeline/imagedefinitions.json
artifacts:
  files:
    - pipeline/imagedefinitions.json
