version: 0.2
env:
  variables:
    ECR_REPO: "778265707519.dkr.ecr.us-east-1.amazonaws.com/event-booking-backend"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}-$(date +%Y%m%d%H%M%S)

  build:
    commands:
      - echo Building backend image...
      - docker build -t $ECR_REPO:$IMAGE_TAG ./backend

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push $ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"backend","imageUri":"%s"}]' "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
