CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id INT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

INSERT INTO events (title, date) VALUES
  ('AWS Immersion Day', DATE_ADD(CURDATE(), INTERVAL 7 DAY)),
  ('Modern DevOps on AWS', DATE_ADD(CURDATE(), INTERVAL 14 DAY)),
  ('Serverless Best Practices', DATE_ADD(CURDATE(), INTERVAL 21 DAY))
ON DUPLICATE KEY UPDATE title = title;

